import { mkdir, readFile, writeFile } from "node:fs/promises";
import { type ForwardLedger } from "../lib/forward.ts";
import { type Phase5Ledger } from "../lib/phase5-forward.ts";
import { assertProductionConfigIntegrity, type ProductionConfig } from "../lib/production.ts";
import { updateLifecycleReview, type LifecycleInputStatus, type LifecycleLedger, type RuntimeStatus } from "../lib/lifecycle-review.ts";
const root=new URL("../github-pages/public/data/",import.meta.url);await mkdir(root,{recursive:true});
const required=async<T>(name:string):Promise<T>=>{try{return JSON.parse(await readFile(new URL(name,root),"utf8")) as T}catch(error){throw Error(`STATE-006: required ${name} is missing/corrupt; refusing lifecycle reset (${error instanceof Error?error.message:String(error)})`)}};
const optional=async<T>(name:string,fallback:T):Promise<T>=>{try{return JSON.parse(await readFile(new URL(name,root),"utf8")) as T}catch{return fallback}};
const phase5=await required<Phase5Ledger>("phase-5-forward-ledger.json"),forward=await required<ForwardLedger>("forward-ledger.json"),production=await required<ProductionConfig>("production-config.json"),prior=await required<LifecycleLedger>("lifecycle-review.json");
if(phase5.schemaVersion!==1||phase5.appendOnly!==true||forward.schemaVersion!==1||forward.appendOnly!==true||prior.schemaVersion!==1||prior.appendOnly!==true)throw Error("STATE-007: lifecycle authority ledger integrity failed");assertProductionConfigIntegrity(production);
const phase5Status=await optional<LifecycleInputStatus|null>("phase-5-forward-status.json",null),runtimeStatus=await optional<RuntimeStatus|null>("status.json",null),now=new Date().toISOString();
const ledger=updateLifecycleReview({phase5,forward,production,phase5Status,runtimeStatus,prior,now});await writeFile(new URL("lifecycle-review.json",root),JSON.stringify(ledger,null,2)+"\n");console.log(`${ledger.current.stage}: ${ledger.current.systemDecision} / ${ledger.current.userAction}`);
